### ISSUE TITLE
Emit Non-Zero Exit Status on Error

### ISSUE THREAD

**Issue by sanbox-irl** [YarnSpinnerTool/YarnSpinner-Console#26]
Right now, `ysc` always returns `0`, even on error. This makes piloting ysc with other tools much harder, since we must devolve into checking if the `stdout` is empty or not. (Fwiw, I'm not sure what the politics of stdout or stderr are! The name would suggest stderr is better, but I've never really seen a pattern in other code).

**Comment by sanbox-irl** [comment]
This is probably a good first issue -- I'm on vacation soon but would love to tackle this fella myself

**Comment by McJones** [comment]
fixed by your own PR, thanks for that
